name: sass_linter
version: 1.3.0-dev
description: A Sass implementation in Dart.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/sass/TODO

#executables:
#  dart-sass: sass

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  sass: "^1.0.0"
  source_span: "^1.4.0"

dev_dependencies:
  dart_style: "^1.0.0"
  test: "^0.12.29"
