name: sass_linter
version: 1.3.0-dev
description: A Sass linter
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  meta: "^1.0.0"
  sass: "^1.0.0"
  source_span: "^1.4.0"

dev_dependencies:
  test: "^0.12.29"
